import type { NextPage } from "next";
import Head from "next/head";
import BookingForm from "../components/BookingForm";
import Map from "../components/Map";

const Home: NextPage = () => {
   return (
      <div className="bg-primary h-screen flex">
         <Head>
            <title>Cabby: Home</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <div className="w-[50%] bg-gray-500 h-full">
            <Map />
         </div>
         <div className="w-[50%] bg-gray-100 h-full">
            <div className="p-10">
               <div className="flex items-center justify-between">
                  <div>
                     <h1 className="text-2xl font-bold">Hi, Jhon Doe</h1>
                     <p className="tracking-wider">
                        Book your new ride with us 🚖
                     </p>
                  </div>
                  <span className="text-blue-700 font-bold cursor-pointer">
                     Ride History
                  </span>
               </div>
               <BookingForm />
            </div>
         </div>
      </div>
   );
};

export default Home;
